# Generated by Django 3.1.6 on 2021-07-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('scatid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=100)),
                ('subcatnm', models.CharField(max_length=100)),
                ('subcaticon', models.CharField(max_length=1000)),
                ('sprice', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
